name: sample-test-workflow

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  display-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
        
      - name: Display Branch Name
        run: echo "Current Branch:${{ steps.extract_branch.outputs.branch }}"
