name: Sync template repo

on:
  # cronjob trigger
  schedule:
    - cron: "*/5 0 * * *"
  # manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
    
jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger the workflow_dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run sample.yml -R $GITHUB_REPOSITORY --ref develop

