name: Sync template repo

on:
  # cronjob trigger
  schedule:
    - cron: "*/5 0 * * *"
  # manual trigger
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
    
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger sample workflow
        uses: mb-viswesh/workflows-test/.github/workflows/schedule.yml@latest
        with:
          workflow: sample.yml
          token: ${{ steps.generate_token.outputs.token }}          
          ref: develop
